// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/domain/entities"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	ports "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/domain/ports"

	mock "github.com/stretchr/testify/mock"

	time "time"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/domain/vos"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, category
func (_m *CategoryRepository) Add(ctx context.Context, category *entities.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CategoryRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entities.Category
func (_e *CategoryRepository_Expecter) Add(ctx interface{}, category interface{}) *CategoryRepository_Add_Call {
	return &CategoryRepository_Add_Call{Call: _e.mock.On("Add", ctx, category)}
}

func (_c *CategoryRepository_Add_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Category))
	})
	return _c
}

func (_c *CategoryRepository_Add_Call) Return(_a0 error) *CategoryRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Add_Call) RunAndReturn(run func(context.Context, *entities.Category) error) *CategoryRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function with given fields: ctx, userID, name, parentID, excludeID
func (_m *CategoryRepository) ExistsByName(ctx context.Context, userID identityvo.UserID, name vos.CategoryName, parentID *vos.CategoryID, excludeID *vos.CategoryID) (bool, error) {
	ret := _m.Called(ctx, userID, name, parentID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryName, *vos.CategoryID, *vos.CategoryID) (bool, error)); ok {
		return rf(ctx, userID, name, parentID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryName, *vos.CategoryID, *vos.CategoryID) bool); ok {
		r0 = rf(ctx, userID, name, parentID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CategoryName, *vos.CategoryID, *vos.CategoryID) error); ok {
		r1 = rf(ctx, userID, name, parentID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type CategoryRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - name vos.CategoryName
//   - parentID *vos.CategoryID
//   - excludeID *vos.CategoryID
func (_e *CategoryRepository_Expecter) ExistsByName(ctx interface{}, userID interface{}, name interface{}, parentID interface{}, excludeID interface{}) *CategoryRepository_ExistsByName_Call {
	return &CategoryRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, userID, name, parentID, excludeID)}
}

func (_c *CategoryRepository_ExistsByName_Call) Run(run func(ctx context.Context, userID identityvo.UserID, name vos.CategoryName, parentID *vos.CategoryID, excludeID *vos.CategoryID)) *CategoryRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryName), args[3].(*vos.CategoryID), args[4].(*vos.CategoryID))
	})
	return _c
}

func (_c *CategoryRepository_ExistsByName_Call) Return(_a0 bool, _a1 error) *CategoryRepository_ExistsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_ExistsByName_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryName, *vos.CategoryID, *vos.CategoryID) (bool, error)) *CategoryRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveChildren provides a mock function with given fields: ctx, userID, parentID
func (_m *CategoryRepository) GetActiveChildren(ctx context.Context, userID identityvo.UserID, parentID vos.CategoryID) ([]entities.Category, error) {
	ret := _m.Called(ctx, userID, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveChildren")
	}

	var r0 []entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) ([]entities.Category, error)); ok {
		return rf(ctx, userID, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) []entities.Category); ok {
		r0 = rf(ctx, userID, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CategoryID) error); ok {
		r1 = rf(ctx, userID, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_GetActiveChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveChildren'
type CategoryRepository_GetActiveChildren_Call struct {
	*mock.Call
}

// GetActiveChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - parentID vos.CategoryID
func (_e *CategoryRepository_Expecter) GetActiveChildren(ctx interface{}, userID interface{}, parentID interface{}) *CategoryRepository_GetActiveChildren_Call {
	return &CategoryRepository_GetActiveChildren_Call{Call: _e.mock.On("GetActiveChildren", ctx, userID, parentID)}
}

func (_c *CategoryRepository_GetActiveChildren_Call) Run(run func(ctx context.Context, userID identityvo.UserID, parentID vos.CategoryID)) *CategoryRepository_GetActiveChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryID))
	})
	return _c
}

func (_c *CategoryRepository_GetActiveChildren_Call) Return(_a0 []entities.Category, _a1 error) *CategoryRepository_GetActiveChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_GetActiveChildren_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryID) ([]entities.Category, error)) *CategoryRepository_GetActiveChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *CategoryRepository) GetByID(ctx context.Context, userID identityvo.UserID, id vos.CategoryID) (*entities.Category, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) (*entities.Category, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) *entities.Category); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CategoryID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id vos.CategoryID
func (_e *CategoryRepository_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *CategoryRepository_GetByID_Call {
	return &CategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *CategoryRepository_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.CategoryID)) *CategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryID))
	})
	return _c
}

func (_c *CategoryRepository_GetByID_Call) Return(_a0 *entities.Category, _a1 error) *CategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryID) (*entities.Category, error)) *CategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDIncludingDeleted provides a mock function with given fields: ctx, userID, id
func (_m *CategoryRepository) GetByIDIncludingDeleted(ctx context.Context, userID identityvo.UserID, id vos.CategoryID) (*entities.Category, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDIncludingDeleted")
	}

	var r0 *entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) (*entities.Category, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) *entities.Category); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CategoryID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_GetByIDIncludingDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDIncludingDeleted'
type CategoryRepository_GetByIDIncludingDeleted_Call struct {
	*mock.Call
}

// GetByIDIncludingDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id vos.CategoryID
func (_e *CategoryRepository_Expecter) GetByIDIncludingDeleted(ctx interface{}, userID interface{}, id interface{}) *CategoryRepository_GetByIDIncludingDeleted_Call {
	return &CategoryRepository_GetByIDIncludingDeleted_Call{Call: _e.mock.On("GetByIDIncludingDeleted", ctx, userID, id)}
}

func (_c *CategoryRepository_GetByIDIncludingDeleted_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.CategoryID)) *CategoryRepository_GetByIDIncludingDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryID))
	})
	return _c
}

func (_c *CategoryRepository_GetByIDIncludingDeleted_Call) Return(_a0 *entities.Category, _a1 error) *CategoryRepository_GetByIDIncludingDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_GetByIDIncludingDeleted_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryID) (*entities.Category, error)) *CategoryRepository_GetByIDIncludingDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filter
func (_m *CategoryRepository) List(ctx context.Context, userID identityvo.UserID, filter ports.ListFilter) ([]entities.Category, int64, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, ports.ListFilter) ([]entities.Category, int64, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, ports.ListFilter) []entities.Category); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, ports.ListFilter) int64); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, identityvo.UserID, ports.ListFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - filter ports.ListFilter
func (_e *CategoryRepository_Expecter) List(ctx interface{}, userID interface{}, filter interface{}) *CategoryRepository_List_Call {
	return &CategoryRepository_List_Call{Call: _e.mock.On("List", ctx, userID, filter)}
}

func (_c *CategoryRepository_List_Call) Run(run func(ctx context.Context, userID identityvo.UserID, filter ports.ListFilter)) *CategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(ports.ListFilter))
	})
	return _c
}

func (_c *CategoryRepository_List_Call) Return(_a0 []entities.Category, _a1 int64, _a2 error) *CategoryRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CategoryRepository_List_Call) RunAndReturn(run func(context.Context, identityvo.UserID, ports.ListFilter) ([]entities.Category, int64, error)) *CategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteCascade provides a mock function with given fields: ctx, userID, rootID, deletedAt
func (_m *CategoryRepository) SoftDeleteCascade(ctx context.Context, userID identityvo.UserID, rootID vos.CategoryID, deletedAt time.Time) error {
	ret := _m.Called(ctx, userID, rootID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCascade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID, time.Time) error); ok {
		r0 = rf(ctx, userID, rootID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_SoftDeleteCascade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteCascade'
type CategoryRepository_SoftDeleteCascade_Call struct {
	*mock.Call
}

// SoftDeleteCascade is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - rootID vos.CategoryID
//   - deletedAt time.Time
func (_e *CategoryRepository_Expecter) SoftDeleteCascade(ctx interface{}, userID interface{}, rootID interface{}, deletedAt interface{}) *CategoryRepository_SoftDeleteCascade_Call {
	return &CategoryRepository_SoftDeleteCascade_Call{Call: _e.mock.On("SoftDeleteCascade", ctx, userID, rootID, deletedAt)}
}

func (_c *CategoryRepository_SoftDeleteCascade_Call) Run(run func(ctx context.Context, userID identityvo.UserID, rootID vos.CategoryID, deletedAt time.Time)) *CategoryRepository_SoftDeleteCascade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryID), args[3].(time.Time))
	})
	return _c
}

func (_c *CategoryRepository_SoftDeleteCascade_Call) Return(_a0 error) *CategoryRepository_SoftDeleteCascade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_SoftDeleteCascade_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryID, time.Time) error) *CategoryRepository_SoftDeleteCascade_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *CategoryRepository) Update(ctx context.Context, category *entities.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entities.Category
func (_e *CategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *CategoryRepository_Update_Call {
	return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Category))
	})
	return _c
}

func (_c *CategoryRepository_Update_Call) Return(_a0 error) *CategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Category) error) *CategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
