apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financialapi
  name: financialapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financialapi
  template:
    metadata:
      labels:
        app: financialapi
    spec:
      containers:
        - name: financialapi
          image: jailtonjunior/financialcontrol:v1
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: ENVIRONMENT
              value: Production
            - name: TZ
              value: America/Sao_Paulo
          ports:
            - containerPort: 4000
