apiVersion: v1
kind: ConfigMap
metadata:
  name: financialapi-config
data:
  ENVIRONMENT: "Production"
  TZ: "America/Sao_Paulo"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financialapi
  name: financialapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financialapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: financialapi
    spec:
      containers:
        - name: financialapi
          image: jailtonjunior/financial_api:v37
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
          envFrom:
            - configMapRef:
                name: financialapi-config
          ports:
            - containerPort: 4000
