// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/application/dtos"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticateUser is an autogenerated mock type for the AuthenticateUser type
type AuthenticateUser struct {
	mock.Mock
}

type AuthenticateUser_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticateUser) EXPECT() *AuthenticateUser_Expecter {
	return &AuthenticateUser_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *AuthenticateUser) Execute(ctx context.Context, in dtos.AuthRequest) (dtos.AuthResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.AuthRequest) (dtos.AuthResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.AuthRequest) dtos.AuthResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dtos.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.AuthRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticateUser_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AuthenticateUser_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in dtos.AuthRequest
func (_e *AuthenticateUser_Expecter) Execute(ctx interface{}, in interface{}) *AuthenticateUser_Execute_Call {
	return &AuthenticateUser_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *AuthenticateUser_Execute_Call) Run(run func(ctx context.Context, in dtos.AuthRequest)) *AuthenticateUser_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.AuthRequest))
	})
	return _c
}

func (_c *AuthenticateUser_Execute_Call) Return(_a0 dtos.AuthResponse, _a1 error) *AuthenticateUser_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticateUser_Execute_Call) RunAndReturn(run func(context.Context, dtos.AuthRequest) (dtos.AuthResponse, error)) *AuthenticateUser_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticateUser creates a new instance of AuthenticateUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticateUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticateUser {
	mock := &AuthenticateUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
