// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/application/dtos"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/application/usecase"
)

// CreateUser is an autogenerated mock type for the CreateUser type
type CreateUser struct {
	mock.Mock
}

type CreateUser_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateUser) EXPECT() *CreateUser_Expecter {
	return &CreateUser_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *CreateUser) Execute(ctx context.Context, in dtos.UserRequest) (usecase.CreateUserResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecase.CreateUserResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UserRequest) (usecase.CreateUserResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UserRequest) usecase.CreateUserResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecase.CreateUserResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.UserRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateUser_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in dtos.UserRequest
func (_e *CreateUser_Expecter) Execute(ctx interface{}, in interface{}) *CreateUser_Execute_Call {
	return &CreateUser_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *CreateUser_Execute_Call) Run(run func(ctx context.Context, in dtos.UserRequest)) *CreateUser_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dtos.UserRequest))
	})
	return _c
}

func (_c *CreateUser_Execute_Call) Return(_a0 usecase.CreateUserResult, _a1 error) *CreateUser_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateUser_Execute_Call) RunAndReturn(run func(context.Context, dtos.UserRequest) (usecase.CreateUserResult, error)) *CreateUser_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateUser creates a new instance of CreateUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateUser {
	mock := &CreateUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
