// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/application/dtos"
	mock "github.com/stretchr/testify/mock"
)

// GetAuthenticatedUser is an autogenerated mock type for the GetAuthenticatedUser type
type GetAuthenticatedUser struct {
	mock.Mock
}

type GetAuthenticatedUser_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAuthenticatedUser) EXPECT() *GetAuthenticatedUser_Expecter {
	return &GetAuthenticatedUser_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *GetAuthenticatedUser) Execute(ctx context.Context) (dtos.MeResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.MeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dtos.MeResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dtos.MeResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dtos.MeResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthenticatedUser_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetAuthenticatedUser_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GetAuthenticatedUser_Expecter) Execute(ctx interface{}) *GetAuthenticatedUser_Execute_Call {
	return &GetAuthenticatedUser_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *GetAuthenticatedUser_Execute_Call) Run(run func(ctx context.Context)) *GetAuthenticatedUser_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GetAuthenticatedUser_Execute_Call) Return(_a0 dtos.MeResponse, _a1 error) *GetAuthenticatedUser_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetAuthenticatedUser_Execute_Call) RunAndReturn(run func(context.Context) (dtos.MeResponse, error)) *GetAuthenticatedUser_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetAuthenticatedUser creates a new instance of GetAuthenticatedUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAuthenticatedUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAuthenticatedUser {
	mock := &GetAuthenticatedUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
