// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	idempotency "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/infrastructure/idempotency"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// IdempotencyRepository is an autogenerated mock type for the IdempotencyRepository type
type IdempotencyRepository struct {
	mock.Mock
}

type IdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IdempotencyRepository) EXPECT() *IdempotencyRepository_Expecter {
	return &IdempotencyRepository_Expecter{mock: &_m.Mock}
}

func (_m *IdempotencyRepository) Get(ctx context.Context, userID identityvo.UserID, endpoint, key string) (*idempotency.IdempotencyHit, error) {
	ret := _m.Called(ctx, userID, endpoint, key)
	if len(ret) == 0 {
		panic("no return value specified for Get")
	}
	var r0 *idempotency.IdempotencyHit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string, string) (*idempotency.IdempotencyHit, error)); ok {
		return rf(ctx, userID, endpoint, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string, string) *idempotency.IdempotencyHit); ok {
		r0 = rf(ctx, userID, endpoint, key)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*idempotency.IdempotencyHit)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, string, string) error); ok {
		r1 = rf(ctx, userID, endpoint, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type IdempotencyRepository_Get_Call struct{ *mock.Call }

func (_e *IdempotencyRepository_Expecter) Get(ctx, userID, endpoint, key interface{}) *IdempotencyRepository_Get_Call {
	return &IdempotencyRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID, endpoint, key)}
}

func (_c *IdempotencyRepository_Get_Call) Run(run func(ctx context.Context, userID identityvo.UserID, endpoint, key string)) *IdempotencyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IdempotencyRepository_Get_Call) Return(_a0 *idempotency.IdempotencyHit, _a1 error) *IdempotencyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdempotencyRepository_Get_Call) RunAndReturn(run func(context.Context, identityvo.UserID, string, string) (*idempotency.IdempotencyHit, error)) *IdempotencyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *IdempotencyRepository) Save(ctx context.Context, rec idempotency.IdempotencyRecord) error {
	ret := _m.Called(ctx, rec)
	if len(ret) == 0 {
		panic("no return value specified for Save")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.IdempotencyRecord) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type IdempotencyRepository_Save_Call struct{ *mock.Call }

func (_e *IdempotencyRepository_Expecter) Save(ctx, rec interface{}) *IdempotencyRepository_Save_Call {
	return &IdempotencyRepository_Save_Call{Call: _e.mock.On("Save", ctx, rec)}
}

func (_c *IdempotencyRepository_Save_Call) Run(run func(ctx context.Context, rec idempotency.IdempotencyRecord)) *IdempotencyRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(idempotency.IdempotencyRecord))
	})
	return _c
}

func (_c *IdempotencyRepository_Save_Call) Return(_a0 error) *IdempotencyRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdempotencyRepository_Save_Call) RunAndReturn(run func(context.Context, idempotency.IdempotencyRecord) error) *IdempotencyRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *IdempotencyRepository) PurgeExpired(ctx context.Context, now time.Time) (int64, error) {
	ret := _m.Called(ctx, now)
	if len(ret) == 0 {
		panic("no return value specified for PurgeExpired")
	}
	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type IdempotencyRepository_PurgeExpired_Call struct{ *mock.Call }

func (_e *IdempotencyRepository_Expecter) PurgeExpired(ctx, now interface{}) *IdempotencyRepository_PurgeExpired_Call {
	return &IdempotencyRepository_PurgeExpired_Call{Call: _e.mock.On("PurgeExpired", ctx, now)}
}

func (_c *IdempotencyRepository_PurgeExpired_Call) Run(run func(ctx context.Context, now time.Time)) *IdempotencyRepository_PurgeExpired_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(time.Time)) })
	return _c
}

func (_c *IdempotencyRepository_PurgeExpired_Call) Return(_a0 int64, _a1 error) *IdempotencyRepository_PurgeExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdempotencyRepository_PurgeExpired_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *IdempotencyRepository_PurgeExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdempotencyRepository creates a new instance of IdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdempotencyRepository {
	mock := &IdempotencyRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
