// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/jailtonjunior94/financialcontrol-api/pkg/jwt"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Issuer is an autogenerated mock type for the Issuer type
type Issuer struct {
	mock.Mock
}

type Issuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Issuer) EXPECT() *Issuer_Expecter {
	return &Issuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, id
func (_m *Issuer) Issue(ctx context.Context, id jwt.Identity) (string, time.Time, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Identity) (string, time.Time, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Identity) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, jwt.Identity) time.Time); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(context.Context, jwt.Identity) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Issuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type Issuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - id jwt.Identity
func (_e *Issuer_Expecter) Issue(ctx interface{}, id interface{}) *Issuer_Issue_Call {
	return &Issuer_Issue_Call{Call: _e.mock.On("Issue", ctx, id)}
}

func (_c *Issuer_Issue_Call) Run(run func(ctx context.Context, id jwt.Identity)) *Issuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(jwt.Identity))
	})
	return _c
}

func (_c *Issuer_Issue_Call) Return(token string, expiresAt time.Time, err error) *Issuer_Issue_Call {
	_c.Call.Return(token, expiresAt, err)
	return _c
}

func (_c *Issuer_Issue_Call) RunAndReturn(run func(context.Context, jwt.Identity) (string, time.Time, error)) *Issuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewIssuer creates a new instance of Issuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Issuer {
	mock := &Issuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
