// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/jailtonjunior94/financialcontrol-api/pkg/jwt"
	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

type Parser_Expecter struct {
	mock *mock.Mock
}

func (_m *Parser) EXPECT() *Parser_Expecter {
	return &Parser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: ctx, token
func (_m *Parser) Parse(ctx context.Context, token string) (jwt.Identity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 jwt.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jwt.Identity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jwt.Identity); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(jwt.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Parser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type Parser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Parser_Expecter) Parse(ctx interface{}, token interface{}) *Parser_Parse_Call {
	return &Parser_Parse_Call{Call: _e.mock.On("Parse", ctx, token)}
}

func (_c *Parser_Parse_Call) Run(run func(ctx context.Context, token string)) *Parser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Parser_Parse_Call) Return(_a0 jwt.Identity, _a1 error) *Parser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Parser_Parse_Call) RunAndReturn(run func(context.Context, string) (jwt.Identity, error)) *Parser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
