environment: Development
mssql:
  connectionString: "sqlserver://sa:@stefany@1994@localhost:1433?database=FinancialControlDB"
security:
  expirationAt: 1
  jwtSecret: "RmluYW5jaWFsQ29udHJvbEFtYmllbnRlRGV2ZWxvcA=="
