environment: "Development"
mssql:
  connectionString: "sqlserver://sa:@stefany@1994@localhost:1433?database=FinancialControlDB"
security:
  expirationAt: 30
  jwtSecret: "5d64937afc75e2ba2e77b237d33ca633"
