environment: Production
mssql:
  connectionString: "sqlserver://sa:@docker@2021@sqlserver-service?database=FinancialControlDB"
security:
  expirationAt: 1
  jwtSecret: "RmluYW5jaWFsQ29udHJvbEFtYmllbnRlUHJvZHVjdGlvbg=="
