environment: Production
mssql:
  connectionString: "sqlserver://DB_A453C8_FinancialControl_admin:@stefany@1994@SQL5053.site4now.net?database=DB_A453C8_FinancialControl"
security:
  expirationAt: 1
  jwtSecret: "RmluYW5jaWFsQ29udHJvbEFtYmllbnRlUHJvZHVjdGlvbg=="
