environment: Staging
mssql:
  connectionString: "sqlserver://sa:@docker@2021@mssql?database=FinancialControlDB"
security:
  expirationAt: 1
  jwtSecret: "RmluYW5jaWFsQ29udHJvbEFtYmllbnRlU3RhZ2luZw=="
