apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-api
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jailton.junior94@outlook.com
    privateKeySecretRef:
      name: letsencrypt-api-tls
    solvers:
      - http01:
          ingress:
            class: nginx
