// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type AnticipateInstallment struct {
	mock.Mock
}

type AnticipateInstallment_Expecter struct {
	mock *mock.Mock
}

func (_m *AnticipateInstallment) EXPECT() *AnticipateInstallment_Expecter {
	return &AnticipateInstallment_Expecter{mock: &_m.Mock}
}

func (_m *AnticipateInstallment) Execute(ctx context.Context, userID identityvo.UserID, txID vos.TransactionID, installmentID vos.InstallmentID) (dtos.TransactionResponse, error) {
	ret := _m.Called(ctx, userID, txID, installmentID)
	var r0 dtos.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID, vos.InstallmentID) (dtos.TransactionResponse, error)); ok {
		return rf(ctx, userID, txID, installmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID, vos.InstallmentID) dtos.TransactionResponse); ok {
		r0 = rf(ctx, userID, txID, installmentID)
	} else {
		r0 = ret.Get(0).(dtos.TransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.TransactionID, vos.InstallmentID) error); ok {
		r1 = rf(ctx, userID, txID, installmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type AnticipateInstallment_Execute_Call struct{ *mock.Call }

func (_e *AnticipateInstallment_Expecter) Execute(ctx, userID, txID, installmentID interface{}) *AnticipateInstallment_Execute_Call {
	return &AnticipateInstallment_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, txID, installmentID)}
}

func (_c *AnticipateInstallment_Execute_Call) Return(r0 dtos.TransactionResponse, r1 error) *AnticipateInstallment_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *AnticipateInstallment_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID, vos.InstallmentID) (dtos.TransactionResponse, error)) *AnticipateInstallment_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewAnticipateInstallment(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnticipateInstallment {
	mock := &AnticipateInstallment{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
