// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type CreateTransaction struct {
	mock.Mock
}

type CreateTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateTransaction) EXPECT() *CreateTransaction_Expecter {
	return &CreateTransaction_Expecter{mock: &_m.Mock}
}

func (_m *CreateTransaction) Execute(ctx context.Context, userID identityvo.UserID, key vos.IdempotencyKey, req dtos.CreateTransactionRequest) (dtos.TransactionResponse, error) {
	ret := _m.Called(ctx, userID, key, req)
	var r0 dtos.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.IdempotencyKey, dtos.CreateTransactionRequest) (dtos.TransactionResponse, error)); ok {
		return rf(ctx, userID, key, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.IdempotencyKey, dtos.CreateTransactionRequest) dtos.TransactionResponse); ok {
		r0 = rf(ctx, userID, key, req)
	} else {
		r0 = ret.Get(0).(dtos.TransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.IdempotencyKey, dtos.CreateTransactionRequest) error); ok {
		r1 = rf(ctx, userID, key, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type CreateTransaction_Execute_Call struct{ *mock.Call }

func (_e *CreateTransaction_Expecter) Execute(ctx, userID, key, req interface{}) *CreateTransaction_Execute_Call {
	return &CreateTransaction_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, key, req)}
}

func (_c *CreateTransaction_Execute_Call) Return(r0 dtos.TransactionResponse, r1 error) *CreateTransaction_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *CreateTransaction_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.IdempotencyKey, dtos.CreateTransactionRequest) (dtos.TransactionResponse, error)) *CreateTransaction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewCreateTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateTransaction {
	mock := &CreateTransaction{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
