// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type DeleteTransaction struct {
	mock.Mock
}

type DeleteTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteTransaction) EXPECT() *DeleteTransaction_Expecter {
	return &DeleteTransaction_Expecter{mock: &_m.Mock}
}

func (_m *DeleteTransaction) Execute(ctx context.Context, userID identityvo.UserID, txID vos.TransactionID) error {
	ret := _m.Called(ctx, userID, txID)
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) error); ok {
		return rf(ctx, userID, txID)
	}
	return ret.Error(0)
}

type DeleteTransaction_Execute_Call struct{ *mock.Call }

func (_e *DeleteTransaction_Expecter) Execute(ctx, userID, txID interface{}) *DeleteTransaction_Execute_Call {
	return &DeleteTransaction_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, txID)}
}

func (_c *DeleteTransaction_Execute_Call) Return(err error) *DeleteTransaction_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeleteTransaction_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID) error) *DeleteTransaction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewDeleteTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteTransaction {
	mock := &DeleteTransaction{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
