// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type GetInvoice struct {
	mock.Mock
}

type GetInvoice_Expecter struct {
	mock *mock.Mock
}

func (_m *GetInvoice) EXPECT() *GetInvoice_Expecter {
	return &GetInvoice_Expecter{mock: &_m.Mock}
}

func (_m *GetInvoice) Execute(ctx context.Context, userID identityvo.UserID, invoiceID vos.InvoiceID) (dtos.InvoiceDetailResponse, error) {
	ret := _m.Called(ctx, userID, invoiceID)
	var r0 dtos.InvoiceDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID) (dtos.InvoiceDetailResponse, error)); ok {
		return rf(ctx, userID, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID) dtos.InvoiceDetailResponse); ok {
		r0 = rf(ctx, userID, invoiceID)
	} else {
		r0 = ret.Get(0).(dtos.InvoiceDetailResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.InvoiceID) error); ok {
		r1 = rf(ctx, userID, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type GetInvoice_Execute_Call struct{ *mock.Call }

func (_e *GetInvoice_Expecter) Execute(ctx, userID, invoiceID interface{}) *GetInvoice_Execute_Call {
	return &GetInvoice_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, invoiceID)}
}

func (_c *GetInvoice_Execute_Call) Return(r0 dtos.InvoiceDetailResponse, r1 error) *GetInvoice_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *GetInvoice_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.InvoiceID) (dtos.InvoiceDetailResponse, error)) *GetInvoice_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewGetInvoice(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetInvoice {
	mock := &GetInvoice{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
