// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type GetTransaction struct {
	mock.Mock
}

type GetTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *GetTransaction) EXPECT() *GetTransaction_Expecter {
	return &GetTransaction_Expecter{mock: &_m.Mock}
}

func (_m *GetTransaction) Execute(ctx context.Context, userID identityvo.UserID, txID vos.TransactionID) (dtos.TransactionResponse, error) {
	ret := _m.Called(ctx, userID, txID)
	var r0 dtos.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) (dtos.TransactionResponse, error)); ok {
		return rf(ctx, userID, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) dtos.TransactionResponse); ok {
		r0 = rf(ctx, userID, txID)
	} else {
		r0 = ret.Get(0).(dtos.TransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.TransactionID) error); ok {
		r1 = rf(ctx, userID, txID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type GetTransaction_Execute_Call struct{ *mock.Call }

func (_e *GetTransaction_Expecter) Execute(ctx, userID, txID interface{}) *GetTransaction_Execute_Call {
	return &GetTransaction_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, txID)}
}

func (_c *GetTransaction_Execute_Call) Return(r0 dtos.TransactionResponse, r1 error) *GetTransaction_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *GetTransaction_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID) (dtos.TransactionResponse, error)) *GetTransaction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewGetTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetTransaction {
	mock := &GetTransaction{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
