// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	filters "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/filters"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type ListInvoices struct {
	mock.Mock
}

type ListInvoices_Expecter struct {
	mock *mock.Mock
}

func (_m *ListInvoices) EXPECT() *ListInvoices_Expecter {
	return &ListInvoices_Expecter{mock: &_m.Mock}
}

func (_m *ListInvoices) Execute(ctx context.Context, userID identityvo.UserID, f filters.InvoiceFilter) (dtos.PaginatedResponse[dtos.InvoiceResponse], error) {
	ret := _m.Called(ctx, userID, f)
	var r0 dtos.PaginatedResponse[dtos.InvoiceResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) (dtos.PaginatedResponse[dtos.InvoiceResponse], error)); ok {
		return rf(ctx, userID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) dtos.PaginatedResponse[dtos.InvoiceResponse]); ok {
		r0 = rf(ctx, userID, f)
	} else {
		r0 = ret.Get(0).(dtos.PaginatedResponse[dtos.InvoiceResponse])
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) error); ok {
		r1 = rf(ctx, userID, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ListInvoices_Execute_Call struct{ *mock.Call }

func (_e *ListInvoices_Expecter) Execute(ctx, userID, f interface{}) *ListInvoices_Execute_Call {
	return &ListInvoices_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, f)}
}

func (_c *ListInvoices_Execute_Call) Return(r0 dtos.PaginatedResponse[dtos.InvoiceResponse], r1 error) *ListInvoices_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *ListInvoices_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, filters.InvoiceFilter) (dtos.PaginatedResponse[dtos.InvoiceResponse], error)) *ListInvoices_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewListInvoices(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListInvoices {
	mock := &ListInvoices{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
