// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	filters "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/filters"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type ListTransactions struct {
	mock.Mock
}

type ListTransactions_Expecter struct {
	mock *mock.Mock
}

func (_m *ListTransactions) EXPECT() *ListTransactions_Expecter {
	return &ListTransactions_Expecter{mock: &_m.Mock}
}

func (_m *ListTransactions) Execute(ctx context.Context, userID identityvo.UserID, f filters.TransactionFilter) (dtos.PaginatedResponse[dtos.TransactionResponse], error) {
	ret := _m.Called(ctx, userID, f)
	var r0 dtos.PaginatedResponse[dtos.TransactionResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.TransactionFilter) (dtos.PaginatedResponse[dtos.TransactionResponse], error)); ok {
		return rf(ctx, userID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.TransactionFilter) dtos.PaginatedResponse[dtos.TransactionResponse]); ok {
		r0 = rf(ctx, userID, f)
	} else {
		r0 = ret.Get(0).(dtos.PaginatedResponse[dtos.TransactionResponse])
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, filters.TransactionFilter) error); ok {
		r1 = rf(ctx, userID, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ListTransactions_Execute_Call struct{ *mock.Call }

func (_e *ListTransactions_Expecter) Execute(ctx, userID, f interface{}) *ListTransactions_Execute_Call {
	return &ListTransactions_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, f)}
}

func (_c *ListTransactions_Execute_Call) Return(r0 dtos.PaginatedResponse[dtos.TransactionResponse], r1 error) *ListTransactions_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *ListTransactions_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, filters.TransactionFilter) (dtos.PaginatedResponse[dtos.TransactionResponse], error)) *ListTransactions_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewListTransactions(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListTransactions {
	mock := &ListTransactions{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
