// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type MonthlySummary struct {
	mock.Mock
}

type MonthlySummary_Expecter struct {
	mock *mock.Mock
}

func (_m *MonthlySummary) EXPECT() *MonthlySummary_Expecter {
	return &MonthlySummary_Expecter{mock: &_m.Mock}
}

func (_m *MonthlySummary) Execute(ctx context.Context, userID identityvo.UserID, period vos.Period) (dtos.MonthlySummaryResponse, error) {
	ret := _m.Called(ctx, userID, period)
	var r0 dtos.MonthlySummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) (dtos.MonthlySummaryResponse, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) dtos.MonthlySummaryResponse); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(dtos.MonthlySummaryResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MonthlySummary_Execute_Call struct{ *mock.Call }

func (_e *MonthlySummary_Expecter) Execute(ctx, userID, period interface{}) *MonthlySummary_Execute_Call {
	return &MonthlySummary_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, period)}
}

func (_c *MonthlySummary_Execute_Call) Return(r0 dtos.MonthlySummaryResponse, r1 error) *MonthlySummary_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *MonthlySummary_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Period) (dtos.MonthlySummaryResponse, error)) *MonthlySummary_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewMonthlySummary(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonthlySummary {
	mock := &MonthlySummary{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
