// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type PayInvoice struct {
	mock.Mock
}

type PayInvoice_Expecter struct {
	mock *mock.Mock
}

func (_m *PayInvoice) EXPECT() *PayInvoice_Expecter {
	return &PayInvoice_Expecter{mock: &_m.Mock}
}

func (_m *PayInvoice) Execute(ctx context.Context, userID identityvo.UserID, invoiceID vos.InvoiceID, req dtos.PayInvoiceRequest) (dtos.InvoiceResponse, error) {
	ret := _m.Called(ctx, userID, invoiceID, req)
	var r0 dtos.InvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID, dtos.PayInvoiceRequest) (dtos.InvoiceResponse, error)); ok {
		return rf(ctx, userID, invoiceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID, dtos.PayInvoiceRequest) dtos.InvoiceResponse); ok {
		r0 = rf(ctx, userID, invoiceID, req)
	} else {
		r0 = ret.Get(0).(dtos.InvoiceResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.InvoiceID, dtos.PayInvoiceRequest) error); ok {
		r1 = rf(ctx, userID, invoiceID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type PayInvoice_Execute_Call struct{ *mock.Call }

func (_e *PayInvoice_Expecter) Execute(ctx, userID, invoiceID, req interface{}) *PayInvoice_Execute_Call {
	return &PayInvoice_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, invoiceID, req)}
}

func (_c *PayInvoice_Execute_Call) Return(r0 dtos.InvoiceResponse, r1 error) *PayInvoice_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *PayInvoice_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.InvoiceID, dtos.PayInvoiceRequest) (dtos.InvoiceResponse, error)) *PayInvoice_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewPayInvoice(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayInvoice {
	mock := &PayInvoice{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
