// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/application/dtos"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

type UpdateTransaction struct {
	mock.Mock
}

type UpdateTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateTransaction) EXPECT() *UpdateTransaction_Expecter {
	return &UpdateTransaction_Expecter{mock: &_m.Mock}
}

func (_m *UpdateTransaction) Execute(ctx context.Context, userID identityvo.UserID, txID vos.TransactionID, req dtos.UpdateTransactionRequest) (dtos.TransactionResponse, error) {
	ret := _m.Called(ctx, userID, txID, req)
	var r0 dtos.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID, dtos.UpdateTransactionRequest) (dtos.TransactionResponse, error)); ok {
		return rf(ctx, userID, txID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID, dtos.UpdateTransactionRequest) dtos.TransactionResponse); ok {
		r0 = rf(ctx, userID, txID, req)
	} else {
		r0 = ret.Get(0).(dtos.TransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.TransactionID, dtos.UpdateTransactionRequest) error); ok {
		r1 = rf(ctx, userID, txID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type UpdateTransaction_Execute_Call struct{ *mock.Call }

func (_e *UpdateTransaction_Expecter) Execute(ctx, userID, txID, req interface{}) *UpdateTransaction_Execute_Call {
	return &UpdateTransaction_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, txID, req)}
}

func (_c *UpdateTransaction_Execute_Call) Return(r0 dtos.TransactionResponse, r1 error) *UpdateTransaction_Execute_Call {
	_c.Call.Return(r0, r1)
	return _c
}

func (_c *UpdateTransaction_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID, dtos.UpdateTransactionRequest) (dtos.TransactionResponse, error)) *UpdateTransaction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func NewUpdateTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateTransaction {
	mock := &UpdateTransaction{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
