// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: plain
func (_m *Hasher) Hash(plain string) (vos.HashedPassword, error) {
	ret := _m.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 vos.HashedPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (vos.HashedPassword, error)); ok {
		return rf(plain)
	}
	if rf, ok := ret.Get(0).(func(string) vos.HashedPassword); ok {
		r0 = rf(plain)
	} else {
		r0 = ret.Get(0).(vos.HashedPassword)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plain string
func (_e *Hasher_Expecter) Hash(plain interface{}) *Hasher_Hash_Call {
	return &Hasher_Hash_Call{Call: _e.mock.On("Hash", plain)}
}

func (_c *Hasher_Hash_Call) Run(run func(plain string)) *Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Hasher_Hash_Call) Return(_a0 vos.HashedPassword, _a1 error) *Hasher_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Hasher_Hash_Call) RunAndReturn(run func(string) (vos.HashedPassword, error)) *Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: hashed, plain
func (_m *Hasher) Verify(hashed vos.HashedPassword, plain string) bool {
	ret := _m.Called(hashed, plain)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(vos.HashedPassword, string) bool); ok {
		r0 = rf(hashed, plain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Hasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Hasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hashed vos.HashedPassword
//   - plain string
func (_e *Hasher_Expecter) Verify(hashed interface{}, plain interface{}) *Hasher_Verify_Call {
	return &Hasher_Verify_Call{Call: _e.mock.On("Verify", hashed, plain)}
}

func (_c *Hasher_Verify_Call) Run(run func(hashed vos.HashedPassword, plain string)) *Hasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(vos.HashedPassword), args[1].(string))
	})
	return _c
}

func (_c *Hasher_Verify_Call) Return(_a0 bool) *Hasher_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hasher_Verify_Call) RunAndReturn(run func(vos.HashedPassword, string) bool) *Hasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
