// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/identity/domain/vos"
)

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, userID, email
func (_m *TokenIssuer) Issue(ctx context.Context, userID vos.UserID, email vos.Email) (string, time.Time, error) {
	ret := _m.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, vos.UserID, vos.Email) (string, time.Time, error)); ok {
		return rf(ctx, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vos.UserID, vos.Email) string); ok {
		r0 = rf(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vos.UserID, vos.Email) time.Time); ok {
		r1 = rf(ctx, userID, email)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(context.Context, vos.UserID, vos.Email) error); ok {
		r2 = rf(ctx, userID, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UserID
//   - email vos.Email
func (_e *TokenIssuer_Expecter) Issue(ctx interface{}, userID interface{}, email interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", ctx, userID, email)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(ctx context.Context, userID vos.UserID, email vos.Email)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UserID), args[2].(vos.Email))
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(token string, expiresAt time.Time, err error) *TokenIssuer_Issue_Call {
	_c.Call.Return(token, expiresAt, err)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(context.Context, vos.UserID, vos.Email) (string, time.Time, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
