apiVersion: v1
kind: Service
metadata:
  name: financialapi-service
  namespace: financialcontrol
spec:
  selector:
    app: financialapi
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer
