// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/entities"

	mock "github.com/stretchr/testify/mock"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/vos"
)

// FlagRepository is an autogenerated mock type for the FlagRepository type
type FlagRepository struct {
	mock.Mock
}

type FlagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FlagRepository) EXPECT() *FlagRepository_Expecter {
	return &FlagRepository_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx, id
func (_m *FlagRepository) Exists(ctx context.Context, id vos.FlagID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vos.FlagID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vos.FlagID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vos.FlagID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlagRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type FlagRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id vos.FlagID
func (_e *FlagRepository_Expecter) Exists(ctx interface{}, id interface{}) *FlagRepository_Exists_Call {
	return &FlagRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *FlagRepository_Exists_Call) Run(run func(ctx context.Context, id vos.FlagID)) *FlagRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.FlagID))
	})
	return _c
}

func (_c *FlagRepository_Exists_Call) Return(_a0 bool, _a1 error) *FlagRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlagRepository_Exists_Call) RunAndReturn(run func(context.Context, vos.FlagID) (bool, error)) *FlagRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *FlagRepository) List(ctx context.Context) ([]entities.Flag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Flag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Flag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlagRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FlagRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FlagRepository_Expecter) List(ctx interface{}) *FlagRepository_List_Call {
	return &FlagRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *FlagRepository_List_Call) Run(run func(ctx context.Context)) *FlagRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FlagRepository_List_Call) Return(_a0 []entities.Flag, _a1 error) *FlagRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlagRepository_List_Call) RunAndReturn(run func(context.Context) ([]entities.Flag, error)) *FlagRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewFlagRepository creates a new instance of FlagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagRepository {
	mock := &FlagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
