apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: financialapi-hpa
  namespace: financialcontrol
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financialapi-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
