package routes

const (
	Token                  = "/token"
	Me                     = "/me"
	Bills                  = "/bills"
	BillDetail             = "/bills/:id"
	BillId                 = "/bills/:billid"
	BillsIdAndItemId       = "/bills/:billid/items/:id"
	Categories             = "/categories"
	CategoryId             = "/categories/:id"
	Transactions           = "/transactions"
	TransactionDetail      = "/transactions/:id"
	TransactionIdAndItemId = "/transactions/:transactionid/items/:id"
	TransactionId          = "/transactions/:transactionid"
	TransactionClone       = "/transactions/:transactionid/clone"
	Users                  = "/users"
	Cards                  = "/cards"
	CardFlags              = "/cards/flags"
	CardId                 = "/cards/:id"
	Invoices               = "/invoices"
	InvoicesImport         = "/invoices-import"
	InvoicesCategories     = "/invoices/:id/categories"
	InvoicesById           = "/invoices/:id"
	InvoicesItems          = "/invoices/:id/items"
)
