// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// CreateCard is an autogenerated mock type for the CreateCard type
type CreateCard struct {
	mock.Mock
}

type CreateCard_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateCard) EXPECT() *CreateCard_Expecter {
	return &CreateCard_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, req
func (_m *CreateCard) Execute(ctx context.Context, userID identityvo.UserID, req dtos.CardRequest) (dtos.CardResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.CardRequest) (dtos.CardResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.CardRequest) dtos.CardResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(dtos.CardResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, dtos.CardRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCard_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateCard_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - req dtos.CardRequest
func (_e *CreateCard_Expecter) Execute(ctx interface{}, userID interface{}, req interface{}) *CreateCard_Execute_Call {
	return &CreateCard_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, req)}
}

func (_c *CreateCard_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, req dtos.CardRequest)) *CreateCard_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(dtos.CardRequest))
	})
	return _c
}

func (_c *CreateCard_Execute_Call) Return(_a0 dtos.CardResponse, _a1 error) *CreateCard_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateCard_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, dtos.CardRequest) (dtos.CardResponse, error)) *CreateCard_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateCard creates a new instance of CreateCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCard {
	mock := &CreateCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
