// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/vos"
)

// DeactivateCard is an autogenerated mock type for the DeactivateCard type
type DeactivateCard struct {
	mock.Mock
}

type DeactivateCard_Expecter struct {
	mock *mock.Mock
}

func (_m *DeactivateCard) EXPECT() *DeactivateCard_Expecter {
	return &DeactivateCard_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *DeactivateCard) Execute(ctx context.Context, userID identityvo.UserID, id vos.CardID) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeactivateCard_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeactivateCard_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id vos.CardID
func (_e *DeactivateCard_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *DeactivateCard_Execute_Call {
	return &DeactivateCard_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *DeactivateCard_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.CardID)) *DeactivateCard_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID))
	})
	return _c
}

func (_c *DeactivateCard_Execute_Call) Return(_a0 error) *DeactivateCard_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeactivateCard_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID) error) *DeactivateCard_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeactivateCard creates a new instance of DeactivateCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeactivateCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeactivateCard {
	mock := &DeactivateCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
