// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/vos"
)

// GetCard is an autogenerated mock type for the GetCard type
type GetCard struct {
	mock.Mock
}

type GetCard_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCard) EXPECT() *GetCard_Expecter {
	return &GetCard_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *GetCard) Execute(ctx context.Context, userID identityvo.UserID, id vos.CardID) (dtos.CardResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) (dtos.CardResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) dtos.CardResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(dtos.CardResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CardID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCard_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetCard_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id vos.CardID
func (_e *GetCard_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *GetCard_Execute_Call {
	return &GetCard_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *GetCard_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.CardID)) *GetCard_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID))
	})
	return _c
}

func (_c *GetCard_Execute_Call) Return(_a0 dtos.CardResponse, _a1 error) *GetCard_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCard_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID) (dtos.CardResponse, error)) *GetCard_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCard creates a new instance of GetCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCard {
	mock := &GetCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
