// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/application/dtos"
	mock "github.com/stretchr/testify/mock"
)

// ListFlags is an autogenerated mock type for the ListFlags type
type ListFlags struct {
	mock.Mock
}

type ListFlags_Expecter struct {
	mock *mock.Mock
}

func (_m *ListFlags) EXPECT() *ListFlags_Expecter {
	return &ListFlags_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ListFlags) Execute(ctx context.Context) ([]dtos.FlagResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []dtos.FlagResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dtos.FlagResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dtos.FlagResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.FlagResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFlags_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListFlags_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ListFlags_Expecter) Execute(ctx interface{}) *ListFlags_Execute_Call {
	return &ListFlags_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ListFlags_Execute_Call) Run(run func(ctx context.Context)) *ListFlags_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ListFlags_Execute_Call) Return(_a0 []dtos.FlagResponse, _a1 error) *ListFlags_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListFlags_Execute_Call) RunAndReturn(run func(context.Context) ([]dtos.FlagResponse, error)) *ListFlags_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListFlags creates a new instance of ListFlags. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListFlags(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListFlags {
	mock := &ListFlags{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
