// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// ListCards is an autogenerated mock type for the ListCards type
type ListCards struct {
	mock.Mock
}

type ListCards_Expecter struct {
	mock *mock.Mock
}

func (_m *ListCards) EXPECT() *ListCards_Expecter {
	return &ListCards_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *ListCards) Execute(ctx context.Context, userID identityvo.UserID) ([]dtos.CardResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []dtos.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID) ([]dtos.CardResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID) []dtos.CardResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.CardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCards_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListCards_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
func (_e *ListCards_Expecter) Execute(ctx interface{}, userID interface{}) *ListCards_Execute_Call {
	return &ListCards_Execute_Call{Call: _e.mock.On("Execute", ctx, userID)}
}

func (_c *ListCards_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID)) *ListCards_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID))
	})
	return _c
}

func (_c *ListCards_Execute_Call) Return(_a0 []dtos.CardResponse, _a1 error) *ListCards_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListCards_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID) ([]dtos.CardResponse, error)) *ListCards_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListCards creates a new instance of ListCards. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListCards(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListCards {
	mock := &ListCards{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
