// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	projections "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/projections"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// CardProvider is an autogenerated mock type for the CardProvider type
type CardProvider struct {
	mock.Mock
}

type CardProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CardProvider) EXPECT() *CardProvider_Expecter {
	return &CardProvider_Expecter{mock: &_m.Mock}
}

func (_m *CardProvider) GetByID(ctx context.Context, userID identityvo.UserID, cardID vos.CardID) (projections.CardView, error) {
	ret := _m.Called(ctx, userID, cardID)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 projections.CardView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) (projections.CardView, error)); ok {
		return rf(ctx, userID, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) projections.CardView); ok {
		r0 = rf(ctx, userID, cardID)
	} else {
		r0 = ret.Get(0).(projections.CardView)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CardID) error); ok {
		r1 = rf(ctx, userID, cardID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type CardProvider_GetByID_Call struct{ *mock.Call }

func (_e *CardProvider_Expecter) GetByID(ctx, userID, cardID interface{}) *CardProvider_GetByID_Call {
	return &CardProvider_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, cardID)}
}

func (_c *CardProvider_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, cardID vos.CardID)) *CardProvider_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID))
	})
	return _c
}

func (_c *CardProvider_GetByID_Call) Return(_a0 projections.CardView, _a1 error) *CardProvider_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardProvider_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID) (projections.CardView, error)) *CardProvider_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCardProvider creates a new instance of CardProvider.
func NewCardProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardProvider {
	mock := &CardProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
