// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	projections "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/projections"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// CategoryProvider is an autogenerated mock type for the CategoryProvider type
type CategoryProvider struct {
	mock.Mock
}

type CategoryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryProvider) EXPECT() *CategoryProvider_Expecter {
	return &CategoryProvider_Expecter{mock: &_m.Mock}
}

func (_m *CategoryProvider) GetByID(ctx context.Context, userID identityvo.UserID, categoryID vos.CategoryID) (projections.CategoryView, error) {
	ret := _m.Called(ctx, userID, categoryID)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 projections.CategoryView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) (projections.CategoryView, error)); ok {
		return rf(ctx, userID, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CategoryID) projections.CategoryView); ok {
		r0 = rf(ctx, userID, categoryID)
	} else {
		r0 = ret.Get(0).(projections.CategoryView)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CategoryID) error); ok {
		r1 = rf(ctx, userID, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type CategoryProvider_GetByID_Call struct{ *mock.Call }

func (_e *CategoryProvider_Expecter) GetByID(ctx, userID, categoryID interface{}) *CategoryProvider_GetByID_Call {
	return &CategoryProvider_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, categoryID)}
}

func (_c *CategoryProvider_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, categoryID vos.CategoryID)) *CategoryProvider_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CategoryID))
	})
	return _c
}

func (_c *CategoryProvider_GetByID_Call) Return(_a0 projections.CategoryView, _a1 error) *CategoryProvider_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryProvider_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CategoryID) (projections.CategoryView, error)) *CategoryProvider_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryProvider creates a new instance of CategoryProvider.
func NewCategoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryProvider {
	mock := &CategoryProvider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
