// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// Clock is an autogenerated mock type for the Clock type
type Clock struct {
	mock.Mock
}

type Clock_Expecter struct {
	mock *mock.Mock
}

func (_m *Clock) EXPECT() *Clock_Expecter {
	return &Clock_Expecter{mock: &_m.Mock}
}

func (_m *Clock) Now() time.Time {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for Now")
	}
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		return rf()
	}
	return ret.Get(0).(time.Time)
}

type Clock_Now_Call struct{ *mock.Call }

func (_e *Clock_Expecter) Now() *Clock_Now_Call {
	return &Clock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *Clock_Now_Call) Run(run func()) *Clock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) { run() })
	return _c
}

func (_c *Clock_Now_Call) Return(_a0 time.Time) *Clock_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Clock_Now_Call) RunAndReturn(run func() time.Time) *Clock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewClock creates a new instance of Clock.
func NewClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Clock {
	mock := &Clock{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
