// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
)

// IDGenerator is an autogenerated mock type for the IDGenerator type
type IDGenerator struct {
	mock.Mock
}

type IDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *IDGenerator) EXPECT() *IDGenerator_Expecter {
	return &IDGenerator_Expecter{mock: &_m.Mock}
}

func (_m *IDGenerator) NewTransactionID() vos.TransactionID {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for NewTransactionID")
	}
	if rf, ok := ret.Get(0).(func() vos.TransactionID); ok {
		return rf()
	}
	return ret.Get(0).(vos.TransactionID)
}

func (_m *IDGenerator) NewInstallmentID() vos.InstallmentID {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for NewInstallmentID")
	}
	if rf, ok := ret.Get(0).(func() vos.InstallmentID); ok {
		return rf()
	}
	return ret.Get(0).(vos.InstallmentID)
}

func (_m *IDGenerator) NewInvoiceID() vos.InvoiceID {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for NewInvoiceID")
	}
	if rf, ok := ret.Get(0).(func() vos.InvoiceID); ok {
		return rf()
	}
	return ret.Get(0).(vos.InvoiceID)
}

// NewIDGenerator creates a new instance of IDGenerator.
func NewIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDGenerator {
	mock := &IDGenerator{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
