// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/entities"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// InstallmentRepository is an autogenerated mock type for the InstallmentRepository type
type InstallmentRepository struct {
	mock.Mock
}

type InstallmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InstallmentRepository) EXPECT() *InstallmentRepository_Expecter {
	return &InstallmentRepository_Expecter{mock: &_m.Mock}
}

func (_m *InstallmentRepository) AddBatch(ctx context.Context, items []*entities.Installment) error {
	ret := _m.Called(ctx, items)
	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entities.Installment) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type InstallmentRepository_AddBatch_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) AddBatch(ctx, items interface{}) *InstallmentRepository_AddBatch_Call {
	return &InstallmentRepository_AddBatch_Call{Call: _e.mock.On("AddBatch", ctx, items)}
}

func (_c *InstallmentRepository_AddBatch_Call) Run(run func(ctx context.Context, items []*entities.Installment)) *InstallmentRepository_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].([]*entities.Installment)) })
	return _c
}

func (_c *InstallmentRepository_AddBatch_Call) Return(_a0 error) *InstallmentRepository_AddBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstallmentRepository_AddBatch_Call) RunAndReturn(run func(context.Context, []*entities.Installment) error) *InstallmentRepository_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) UpdateBatch(ctx context.Context, items []*entities.Installment) error {
	ret := _m.Called(ctx, items)
	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entities.Installment) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type InstallmentRepository_UpdateBatch_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) UpdateBatch(ctx, items interface{}) *InstallmentRepository_UpdateBatch_Call {
	return &InstallmentRepository_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, items)}
}

func (_c *InstallmentRepository_UpdateBatch_Call) Run(run func(ctx context.Context, items []*entities.Installment)) *InstallmentRepository_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].([]*entities.Installment)) })
	return _c
}

func (_c *InstallmentRepository_UpdateBatch_Call) Return(_a0 error) *InstallmentRepository_UpdateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstallmentRepository_UpdateBatch_Call) RunAndReturn(run func(context.Context, []*entities.Installment) error) *InstallmentRepository_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) SoftDeleteByTransaction(ctx context.Context, userID identityvo.UserID, transactionID vos.TransactionID, at time.Time) error {
	ret := _m.Called(ctx, userID, transactionID, at)
	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByTransaction")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID, time.Time) error); ok {
		r0 = rf(ctx, userID, transactionID, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type InstallmentRepository_SoftDeleteByTransaction_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) SoftDeleteByTransaction(ctx, userID, transactionID, at interface{}) *InstallmentRepository_SoftDeleteByTransaction_Call {
	return &InstallmentRepository_SoftDeleteByTransaction_Call{Call: _e.mock.On("SoftDeleteByTransaction", ctx, userID, transactionID, at)}
}

func (_c *InstallmentRepository_SoftDeleteByTransaction_Call) Run(run func(ctx context.Context, userID identityvo.UserID, transactionID vos.TransactionID, at time.Time)) *InstallmentRepository_SoftDeleteByTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.TransactionID), args[3].(time.Time))
	})
	return _c
}

func (_c *InstallmentRepository_SoftDeleteByTransaction_Call) Return(_a0 error) *InstallmentRepository_SoftDeleteByTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstallmentRepository_SoftDeleteByTransaction_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID, time.Time) error) *InstallmentRepository_SoftDeleteByTransaction_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) ListByInvoice(ctx context.Context, invoiceID vos.InvoiceID) ([]entities.Installment, error) {
	ret := _m.Called(ctx, invoiceID)
	if len(ret) == 0 {
		panic("no return value specified for ListByInvoice")
	}
	var r0 []entities.Installment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vos.InvoiceID) ([]entities.Installment, error)); ok {
		return rf(ctx, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vos.InvoiceID) []entities.Installment); ok {
		r0 = rf(ctx, invoiceID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Installment)
	}
	if rf, ok := ret.Get(1).(func(context.Context, vos.InvoiceID) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InstallmentRepository_ListByInvoice_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) ListByInvoice(ctx, invoiceID interface{}) *InstallmentRepository_ListByInvoice_Call {
	return &InstallmentRepository_ListByInvoice_Call{Call: _e.mock.On("ListByInvoice", ctx, invoiceID)}
}

func (_c *InstallmentRepository_ListByInvoice_Call) Run(run func(ctx context.Context, invoiceID vos.InvoiceID)) *InstallmentRepository_ListByInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(vos.InvoiceID)) })
	return _c
}

func (_c *InstallmentRepository_ListByInvoice_Call) Return(_a0 []entities.Installment, _a1 error) *InstallmentRepository_ListByInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstallmentRepository_ListByInvoice_Call) RunAndReturn(run func(context.Context, vos.InvoiceID) ([]entities.Installment, error)) *InstallmentRepository_ListByInvoice_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) ListByTransaction(ctx context.Context, transactionID vos.TransactionID) ([]entities.Installment, error) {
	ret := _m.Called(ctx, transactionID)
	if len(ret) == 0 {
		panic("no return value specified for ListByTransaction")
	}
	var r0 []entities.Installment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vos.TransactionID) ([]entities.Installment, error)); ok {
		return rf(ctx, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vos.TransactionID) []entities.Installment); ok {
		r0 = rf(ctx, transactionID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Installment)
	}
	if rf, ok := ret.Get(1).(func(context.Context, vos.TransactionID) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InstallmentRepository_ListByTransaction_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) ListByTransaction(ctx, transactionID interface{}) *InstallmentRepository_ListByTransaction_Call {
	return &InstallmentRepository_ListByTransaction_Call{Call: _e.mock.On("ListByTransaction", ctx, transactionID)}
}

func (_c *InstallmentRepository_ListByTransaction_Call) Run(run func(ctx context.Context, transactionID vos.TransactionID)) *InstallmentRepository_ListByTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(vos.TransactionID)) })
	return _c
}

func (_c *InstallmentRepository_ListByTransaction_Call) Return(_a0 []entities.Installment, _a1 error) *InstallmentRepository_ListByTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstallmentRepository_ListByTransaction_Call) RunAndReturn(run func(context.Context, vos.TransactionID) ([]entities.Installment, error)) *InstallmentRepository_ListByTransaction_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) HasClosedOrPaidForTransaction(ctx context.Context, transactionID vos.TransactionID) (bool, error) {
	ret := _m.Called(ctx, transactionID)
	if len(ret) == 0 {
		panic("no return value specified for HasClosedOrPaidForTransaction")
	}
	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vos.TransactionID) (bool, error)); ok {
		return rf(ctx, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vos.TransactionID) bool); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(context.Context, vos.TransactionID) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InstallmentRepository_HasClosedOrPaidForTransaction_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) HasClosedOrPaidForTransaction(ctx, transactionID interface{}) *InstallmentRepository_HasClosedOrPaidForTransaction_Call {
	return &InstallmentRepository_HasClosedOrPaidForTransaction_Call{Call: _e.mock.On("HasClosedOrPaidForTransaction", ctx, transactionID)}
}

func (_c *InstallmentRepository_HasClosedOrPaidForTransaction_Call) Run(run func(ctx context.Context, transactionID vos.TransactionID)) *InstallmentRepository_HasClosedOrPaidForTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(vos.TransactionID)) })
	return _c
}

func (_c *InstallmentRepository_HasClosedOrPaidForTransaction_Call) Return(_a0 bool, _a1 error) *InstallmentRepository_HasClosedOrPaidForTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstallmentRepository_HasClosedOrPaidForTransaction_Call) RunAndReturn(run func(context.Context, vos.TransactionID) (bool, error)) *InstallmentRepository_HasClosedOrPaidForTransaction_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InstallmentRepository) SumByMonthCompetence(ctx context.Context, userID identityvo.UserID, period vos.Period) (vos.Money, error) {
	ret := _m.Called(ctx, userID, period)
	if len(ret) == 0 {
		panic("no return value specified for SumByMonthCompetence")
	}
	var r0 vos.Money
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) vos.Money); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(vos.Money)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InstallmentRepository_SumByMonthCompetence_Call struct{ *mock.Call }

func (_e *InstallmentRepository_Expecter) SumByMonthCompetence(ctx, userID, period interface{}) *InstallmentRepository_SumByMonthCompetence_Call {
	return &InstallmentRepository_SumByMonthCompetence_Call{Call: _e.mock.On("SumByMonthCompetence", ctx, userID, period)}
}

func (_c *InstallmentRepository_SumByMonthCompetence_Call) Run(run func(ctx context.Context, userID identityvo.UserID, period vos.Period)) *InstallmentRepository_SumByMonthCompetence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.Period))
	})
	return _c
}

func (_c *InstallmentRepository_SumByMonthCompetence_Call) Return(_a0 vos.Money, _a1 error) *InstallmentRepository_SumByMonthCompetence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstallmentRepository_SumByMonthCompetence_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)) *InstallmentRepository_SumByMonthCompetence_Call {
	_c.Call.Return(run)
	return _c
}

// NewInstallmentRepository creates a new instance of InstallmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInstallmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstallmentRepository {
	mock := &InstallmentRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
