// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/entities"
	filters "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/filters"
	ports "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/ports"
	projections "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/projections"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// InvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type InvoiceRepository struct {
	mock.Mock
}

type InvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceRepository) EXPECT() *InvoiceRepository_Expecter {
	return &InvoiceRepository_Expecter{mock: &_m.Mock}
}

func (_m *InvoiceRepository) AssignOrCreateOpen(ctx context.Context, userID identityvo.UserID, cardID vos.CardID, occurredAtLocal time.Time, card projections.CardView, clock ports.Clock) (*entities.Invoice, error) {
	ret := _m.Called(ctx, userID, cardID, occurredAtLocal, card, clock)
	if len(ret) == 0 {
		panic("no return value specified for AssignOrCreateOpen")
	}
	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID, time.Time, projections.CardView, ports.Clock) (*entities.Invoice, error)); ok {
		return rf(ctx, userID, cardID, occurredAtLocal, card, clock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID, time.Time, projections.CardView, ports.Clock) *entities.Invoice); ok {
		r0 = rf(ctx, userID, cardID, occurredAtLocal, card, clock)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*entities.Invoice)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CardID, time.Time, projections.CardView, ports.Clock) error); ok {
		r1 = rf(ctx, userID, cardID, occurredAtLocal, card, clock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceRepository_AssignOrCreateOpen_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) AssignOrCreateOpen(ctx, userID, cardID, occurredAtLocal, card, clock interface{}) *InvoiceRepository_AssignOrCreateOpen_Call {
	return &InvoiceRepository_AssignOrCreateOpen_Call{Call: _e.mock.On("AssignOrCreateOpen", ctx, userID, cardID, occurredAtLocal, card, clock)}
}

func (_c *InvoiceRepository_AssignOrCreateOpen_Call) Run(run func(ctx context.Context, userID identityvo.UserID, cardID vos.CardID, occurredAtLocal time.Time, card projections.CardView, clock ports.Clock)) *InvoiceRepository_AssignOrCreateOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID), args[3].(time.Time), args[4].(projections.CardView), args[5].(ports.Clock))
	})
	return _c
}

func (_c *InvoiceRepository_AssignOrCreateOpen_Call) Return(_a0 *entities.Invoice, _a1 error) *InvoiceRepository_AssignOrCreateOpen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceRepository_AssignOrCreateOpen_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID, time.Time, projections.CardView, ports.Clock) (*entities.Invoice, error)) *InvoiceRepository_AssignOrCreateOpen_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) GetByID(ctx context.Context, userID identityvo.UserID, id vos.InvoiceID) (*entities.Invoice, error) {
	ret := _m.Called(ctx, userID, id)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID) (*entities.Invoice, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.InvoiceID) *entities.Invoice); ok {
		r0 = rf(ctx, userID, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*entities.Invoice)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.InvoiceID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceRepository_GetByID_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) GetByID(ctx, userID, id interface{}) *InvoiceRepository_GetByID_Call {
	return &InvoiceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *InvoiceRepository_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.InvoiceID)) *InvoiceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.InvoiceID))
	})
	return _c
}

func (_c *InvoiceRepository_GetByID_Call) Return(_a0 *entities.Invoice, _a1 error) *InvoiceRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceRepository_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.InvoiceID) (*entities.Invoice, error)) *InvoiceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) List(ctx context.Context, userID identityvo.UserID, f filters.InvoiceFilter) ([]entities.Invoice, int64, error) {
	ret := _m.Called(ctx, userID, f)
	if len(ret) == 0 {
		panic("no return value specified for List")
	}
	var r0 []entities.Invoice
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) ([]entities.Invoice, int64, error)); ok {
		return rf(ctx, userID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) []entities.Invoice); ok {
		r0 = rf(ctx, userID, f)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Invoice)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) int64); ok {
		r1 = rf(ctx, userID, f)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, identityvo.UserID, filters.InvoiceFilter) error); ok {
		r2 = rf(ctx, userID, f)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

type InvoiceRepository_List_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) List(ctx, userID, f interface{}) *InvoiceRepository_List_Call {
	return &InvoiceRepository_List_Call{Call: _e.mock.On("List", ctx, userID, f)}
}

func (_c *InvoiceRepository_List_Call) Run(run func(ctx context.Context, userID identityvo.UserID, f filters.InvoiceFilter)) *InvoiceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(filters.InvoiceFilter))
	})
	return _c
}

func (_c *InvoiceRepository_List_Call) Return(_a0 []entities.Invoice, _a1 int64, _a2 error) *InvoiceRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *InvoiceRepository_List_Call) RunAndReturn(run func(context.Context, identityvo.UserID, filters.InvoiceFilter) ([]entities.Invoice, int64, error)) *InvoiceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) Update(ctx context.Context, inv *entities.Invoice) error {
	ret := _m.Called(ctx, inv)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Invoice) error); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type InvoiceRepository_Update_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) Update(ctx, inv interface{}) *InvoiceRepository_Update_Call {
	return &InvoiceRepository_Update_Call{Call: _e.mock.On("Update", ctx, inv)}
}

func (_c *InvoiceRepository_Update_Call) Run(run func(ctx context.Context, inv *entities.Invoice)) *InvoiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(*entities.Invoice)) })
	return _c
}

func (_c *InvoiceRepository_Update_Call) Return(_a0 error) *InvoiceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvoiceRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Invoice) error) *InvoiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) NextOpenFor(ctx context.Context, userID identityvo.UserID, cardID vos.CardID, clock ports.Clock) (*entities.Invoice, error) {
	ret := _m.Called(ctx, userID, cardID, clock)
	if len(ret) == 0 {
		panic("no return value specified for NextOpenFor")
	}
	var r0 *entities.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID, ports.Clock) (*entities.Invoice, error)); ok {
		return rf(ctx, userID, cardID, clock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID, ports.Clock) *entities.Invoice); ok {
		r0 = rf(ctx, userID, cardID, clock)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*entities.Invoice)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CardID, ports.Clock) error); ok {
		r1 = rf(ctx, userID, cardID, clock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceRepository_NextOpenFor_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) NextOpenFor(ctx, userID, cardID, clock interface{}) *InvoiceRepository_NextOpenFor_Call {
	return &InvoiceRepository_NextOpenFor_Call{Call: _e.mock.On("NextOpenFor", ctx, userID, cardID, clock)}
}

func (_c *InvoiceRepository_NextOpenFor_Call) Run(run func(ctx context.Context, userID identityvo.UserID, cardID vos.CardID, clock ports.Clock)) *InvoiceRepository_NextOpenFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID), args[3].(ports.Clock))
	})
	return _c
}

func (_c *InvoiceRepository_NextOpenFor_Call) Return(_a0 *entities.Invoice, _a1 error) *InvoiceRepository_NextOpenFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceRepository_NextOpenFor_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID, ports.Clock) (*entities.Invoice, error)) *InvoiceRepository_NextOpenFor_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) SumPaidInPeriod(ctx context.Context, userID identityvo.UserID, period vos.Period) (vos.Money, error) {
	ret := _m.Called(ctx, userID, period)
	if len(ret) == 0 {
		panic("no return value specified for SumPaidInPeriod")
	}
	var r0 vos.Money
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) vos.Money); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(vos.Money)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceRepository_SumPaidInPeriod_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) SumPaidInPeriod(ctx, userID, period interface{}) *InvoiceRepository_SumPaidInPeriod_Call {
	return &InvoiceRepository_SumPaidInPeriod_Call{Call: _e.mock.On("SumPaidInPeriod", ctx, userID, period)}
}

func (_c *InvoiceRepository_SumPaidInPeriod_Call) Run(run func(ctx context.Context, userID identityvo.UserID, period vos.Period)) *InvoiceRepository_SumPaidInPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.Period))
	})
	return _c
}

func (_c *InvoiceRepository_SumPaidInPeriod_Call) Return(_a0 vos.Money, _a1 error) *InvoiceRepository_SumPaidInPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceRepository_SumPaidInPeriod_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)) *InvoiceRepository_SumPaidInPeriod_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *InvoiceRepository) SumOpenForUser(ctx context.Context, userID identityvo.UserID, period vos.Period) (vos.Money, error) {
	ret := _m.Called(ctx, userID, period)
	if len(ret) == 0 {
		panic("no return value specified for SumOpenForUser")
	}
	var r0 vos.Money
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) vos.Money); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(vos.Money)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceRepository_SumOpenForUser_Call struct{ *mock.Call }

func (_e *InvoiceRepository_Expecter) SumOpenForUser(ctx, userID, period interface{}) *InvoiceRepository_SumOpenForUser_Call {
	return &InvoiceRepository_SumOpenForUser_Call{Call: _e.mock.On("SumOpenForUser", ctx, userID, period)}
}

func (_c *InvoiceRepository_SumOpenForUser_Call) Run(run func(ctx context.Context, userID identityvo.UserID, period vos.Period)) *InvoiceRepository_SumOpenForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.Period))
	})
	return _c
}

func (_c *InvoiceRepository_SumOpenForUser_Call) Return(_a0 vos.Money, _a1 error) *InvoiceRepository_SumOpenForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceRepository_SumOpenForUser_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Period) (vos.Money, error)) *InvoiceRepository_SumOpenForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvoiceRepository creates a new instance of InvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceRepository {
	mock := &InvoiceRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
