// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/entities"
	filters "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/filters"
	ports "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/ports"
	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/finance/domain/vos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

func (_m *TransactionRepository) Add(ctx context.Context, t *entities.Transaction) error {
	ret := _m.Called(ctx, t)
	if len(ret) == 0 {
		panic("no return value specified for Add")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type TransactionRepository_Add_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) Add(ctx, t interface{}) *TransactionRepository_Add_Call {
	return &TransactionRepository_Add_Call{Call: _e.mock.On("Add", ctx, t)}
}

func (_c *TransactionRepository_Add_Call) Run(run func(ctx context.Context, t *entities.Transaction)) *TransactionRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(*entities.Transaction)) })
	return _c
}

func (_c *TransactionRepository_Add_Call) Return(_a0 error) *TransactionRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Add_Call) RunAndReturn(run func(context.Context, *entities.Transaction) error) *TransactionRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) Update(ctx context.Context, t *entities.Transaction) error {
	ret := _m.Called(ctx, t)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type TransactionRepository_Update_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) Update(ctx, t interface{}) *TransactionRepository_Update_Call {
	return &TransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *TransactionRepository_Update_Call) Run(run func(ctx context.Context, t *entities.Transaction)) *TransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) { run(args[0].(context.Context), args[1].(*entities.Transaction)) })
	return _c
}

func (_c *TransactionRepository_Update_Call) Return(_a0 error) *TransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Transaction) error) *TransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) GetByID(ctx context.Context, userID identityvo.UserID, id vos.TransactionID) (*entities.Transaction, error) {
	ret := _m.Called(ctx, userID, id)
	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}
	var r0 *entities.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) (*entities.Transaction, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) *entities.Transaction); ok {
		r0 = rf(ctx, userID, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*entities.Transaction)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.TransactionID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type TransactionRepository_GetByID_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) GetByID(ctx, userID, id interface{}) *TransactionRepository_GetByID_Call {
	return &TransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *TransactionRepository_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.TransactionID)) *TransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.TransactionID))
	})
	return _c
}

func (_c *TransactionRepository_GetByID_Call) Return(_a0 *entities.Transaction, _a1 error) *TransactionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID) (*entities.Transaction, error)) *TransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) List(ctx context.Context, userID identityvo.UserID, f filters.TransactionFilter) ([]entities.Transaction, int64, error) {
	ret := _m.Called(ctx, userID, f)
	if len(ret) == 0 {
		panic("no return value specified for List")
	}
	var r0 []entities.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.TransactionFilter) ([]entities.Transaction, int64, error)); ok {
		return rf(ctx, userID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, filters.TransactionFilter) []entities.Transaction); ok {
		r0 = rf(ctx, userID, f)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]entities.Transaction)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, filters.TransactionFilter) int64); ok {
		r1 = rf(ctx, userID, f)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, identityvo.UserID, filters.TransactionFilter) error); ok {
		r2 = rf(ctx, userID, f)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

type TransactionRepository_List_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) List(ctx, userID, f interface{}) *TransactionRepository_List_Call {
	return &TransactionRepository_List_Call{Call: _e.mock.On("List", ctx, userID, f)}
}

func (_c *TransactionRepository_List_Call) Run(run func(ctx context.Context, userID identityvo.UserID, f filters.TransactionFilter)) *TransactionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(filters.TransactionFilter))
	})
	return _c
}

func (_c *TransactionRepository_List_Call) Return(_a0 []entities.Transaction, _a1 int64, _a2 error) *TransactionRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TransactionRepository_List_Call) RunAndReturn(run func(context.Context, identityvo.UserID, filters.TransactionFilter) ([]entities.Transaction, int64, error)) *TransactionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) SoftDelete(ctx context.Context, t *entities.Transaction, at time.Time) error {
	ret := _m.Called(ctx, t, at)
	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Transaction, time.Time) error); ok {
		r0 = rf(ctx, t, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type TransactionRepository_SoftDelete_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) SoftDelete(ctx, t, at interface{}) *TransactionRepository_SoftDelete_Call {
	return &TransactionRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, t, at)}
}

func (_c *TransactionRepository_SoftDelete_Call) Run(run func(ctx context.Context, t *entities.Transaction, at time.Time)) *TransactionRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Transaction), args[2].(time.Time))
	})
	return _c
}

func (_c *TransactionRepository_SoftDelete_Call) Return(_a0 error) *TransactionRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, *entities.Transaction, time.Time) error) *TransactionRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) HasActiveRefundFor(ctx context.Context, userID identityvo.UserID, original vos.TransactionID) (bool, error) {
	ret := _m.Called(ctx, userID, original)
	if len(ret) == 0 {
		panic("no return value specified for HasActiveRefundFor")
	}
	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) (bool, error)); ok {
		return rf(ctx, userID, original)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.TransactionID) bool); ok {
		r0 = rf(ctx, userID, original)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.TransactionID) error); ok {
		r1 = rf(ctx, userID, original)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type TransactionRepository_HasActiveRefundFor_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) HasActiveRefundFor(ctx, userID, original interface{}) *TransactionRepository_HasActiveRefundFor_Call {
	return &TransactionRepository_HasActiveRefundFor_Call{Call: _e.mock.On("HasActiveRefundFor", ctx, userID, original)}
}

func (_c *TransactionRepository_HasActiveRefundFor_Call) Run(run func(ctx context.Context, userID identityvo.UserID, original vos.TransactionID)) *TransactionRepository_HasActiveRefundFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.TransactionID))
	})
	return _c
}

func (_c *TransactionRepository_HasActiveRefundFor_Call) Return(_a0 bool, _a1 error) *TransactionRepository_HasActiveRefundFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_HasActiveRefundFor_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.TransactionID) (bool, error)) *TransactionRepository_HasActiveRefundFor_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TransactionRepository) SumForSummary(ctx context.Context, userID identityvo.UserID, period vos.Period) (ports.SummaryAggregates, error) {
	ret := _m.Called(ctx, userID, period)
	if len(ret) == 0 {
		panic("no return value specified for SumForSummary")
	}
	var r0 ports.SummaryAggregates
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) (ports.SummaryAggregates, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Period) ports.SummaryAggregates); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(ports.SummaryAggregates)
	}
	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type TransactionRepository_SumForSummary_Call struct{ *mock.Call }

func (_e *TransactionRepository_Expecter) SumForSummary(ctx, userID, period interface{}) *TransactionRepository_SumForSummary_Call {
	return &TransactionRepository_SumForSummary_Call{Call: _e.mock.On("SumForSummary", ctx, userID, period)}
}

func (_c *TransactionRepository_SumForSummary_Call) Run(run func(ctx context.Context, userID identityvo.UserID, period vos.Period)) *TransactionRepository_SumForSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.Period))
	})
	return _c
}

func (_c *TransactionRepository_SumForSummary_Call) Return(_a0 ports.SummaryAggregates, _a1 error) *TransactionRepository_SumForSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_SumForSummary_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Period) (ports.SummaryAggregates, error)) *TransactionRepository_SumForSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
