// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// CreateCategory is an autogenerated mock type for the CreateCategory type
type CreateCategory struct {
	mock.Mock
}

type CreateCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateCategory) EXPECT() *CreateCategory_Expecter {
	return &CreateCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, req
func (_m *CreateCategory) Execute(ctx context.Context, userID identityvo.UserID, req dtos.CategoryRequest) (dtos.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.CategoryRequest) (dtos.CategoryResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.CategoryRequest) dtos.CategoryResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(dtos.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, dtos.CategoryRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - req dtos.CategoryRequest
func (_e *CreateCategory_Expecter) Execute(ctx interface{}, userID interface{}, req interface{}) *CreateCategory_Execute_Call {
	return &CreateCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, req)}
}

func (_c *CreateCategory_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, req dtos.CategoryRequest)) *CreateCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(dtos.CategoryRequest))
	})
	return _c
}

func (_c *CreateCategory_Execute_Call) Return(_a0 dtos.CategoryResponse, _a1 error) *CreateCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateCategory_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, dtos.CategoryRequest) (dtos.CategoryResponse, error)) *CreateCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateCategory creates a new instance of CreateCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCategory {
	mock := &CreateCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
