// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCategory is an autogenerated mock type for the DeleteCategory type
type DeleteCategory struct {
	mock.Mock
}

type DeleteCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCategory) EXPECT() *DeleteCategory_Expecter {
	return &DeleteCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *DeleteCategory) Execute(ctx context.Context, userID identityvo.UserID, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id string
func (_e *DeleteCategory_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *DeleteCategory_Execute_Call {
	return &DeleteCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *DeleteCategory_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id string)) *DeleteCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(string))
	})
	return _c
}

func (_c *DeleteCategory_Execute_Call) Return(_a0 error) *DeleteCategory_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteCategory_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, string) error) *DeleteCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCategory creates a new instance of DeleteCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCategory {
	mock := &DeleteCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
