// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// GetCategory is an autogenerated mock type for the GetCategory type
type GetCategory struct {
	mock.Mock
}

type GetCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCategory) EXPECT() *GetCategory_Expecter {
	return &GetCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *GetCategory) Execute(ctx context.Context, userID identityvo.UserID, id string) (dtos.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string) (dtos.CategoryResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string) dtos.CategoryResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(dtos.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id string
func (_e *GetCategory_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *GetCategory_Execute_Call {
	return &GetCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *GetCategory_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id string)) *GetCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(string))
	})
	return _c
}

func (_c *GetCategory_Execute_Call) Return(_a0 dtos.CategoryResponse, _a1 error) *GetCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCategory_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, string) (dtos.CategoryResponse, error)) *GetCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCategory creates a new instance of GetCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCategory {
	mock := &GetCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
