// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// ListCategories is an autogenerated mock type for the ListCategories type
type ListCategories struct {
	mock.Mock
}

type ListCategories_Expecter struct {
	mock *mock.Mock
}

func (_m *ListCategories) EXPECT() *ListCategories_Expecter {
	return &ListCategories_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, q
func (_m *ListCategories) Execute(ctx context.Context, userID identityvo.UserID, q dtos.ListCategoriesQuery) (dtos.PaginatedResponse[dtos.CategoryResponse], error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.PaginatedResponse[dtos.CategoryResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.ListCategoriesQuery) (dtos.PaginatedResponse[dtos.CategoryResponse], error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, dtos.ListCategoriesQuery) dtos.PaginatedResponse[dtos.CategoryResponse]); ok {
		r0 = rf(ctx, userID, q)
	} else {
		r0 = ret.Get(0).(dtos.PaginatedResponse[dtos.CategoryResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, dtos.ListCategoriesQuery) error); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListCategories_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - q dtos.ListCategoriesQuery
func (_e *ListCategories_Expecter) Execute(ctx interface{}, userID interface{}, q interface{}) *ListCategories_Execute_Call {
	return &ListCategories_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, q)}
}

func (_c *ListCategories_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, q dtos.ListCategoriesQuery)) *ListCategories_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(dtos.ListCategoriesQuery))
	})
	return _c
}

func (_c *ListCategories_Execute_Call) Return(_a0 dtos.PaginatedResponse[dtos.CategoryResponse], _a1 error) *ListCategories_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListCategories_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, dtos.ListCategoriesQuery) (dtos.PaginatedResponse[dtos.CategoryResponse], error)) *ListCategories_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListCategories creates a new instance of ListCategories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListCategories(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListCategories {
	mock := &ListCategories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
