// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/categories/application/dtos"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"
)

// UpdateCategory is an autogenerated mock type for the UpdateCategory type
type UpdateCategory struct {
	mock.Mock
}

type UpdateCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateCategory) EXPECT() *UpdateCategory_Expecter {
	return &UpdateCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id, req
func (_m *UpdateCategory) Execute(ctx context.Context, userID identityvo.UserID, id string, req dtos.CategoryRequest) (dtos.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dtos.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string, dtos.CategoryRequest) (dtos.CategoryResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, string, dtos.CategoryRequest) dtos.CategoryResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(dtos.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, string, dtos.CategoryRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id string
//   - req dtos.CategoryRequest
func (_e *UpdateCategory_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}, req interface{}) *UpdateCategory_Execute_Call {
	return &UpdateCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id, req)}
}

func (_c *UpdateCategory_Execute_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id string, req dtos.CategoryRequest)) *UpdateCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(string), args[3].(dtos.CategoryRequest))
	})
	return _c
}

func (_c *UpdateCategory_Execute_Call) Return(_a0 dtos.CategoryResponse, _a1 error) *UpdateCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpdateCategory_Execute_Call) RunAndReturn(run func(context.Context, identityvo.UserID, string, dtos.CategoryRequest) (dtos.CategoryResponse, error)) *UpdateCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateCategory creates a new instance of UpdateCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateCategory {
	mock := &UpdateCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
