// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/entities"
	identityvo "github.com/jailtonjunior94/financialcontrol-api/pkg/identityvo"

	mock "github.com/stretchr/testify/mock"

	vos "github.com/jailtonjunior94/financialcontrol-api/internal/modules/cards/domain/vos"
)

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

type CardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CardRepository) EXPECT() *CardRepository_Expecter {
	return &CardRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, card
func (_m *CardRepository) Add(ctx context.Context, card *entities.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CardRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - card *entities.Card
func (_e *CardRepository_Expecter) Add(ctx interface{}, card interface{}) *CardRepository_Add_Call {
	return &CardRepository_Add_Call{Call: _e.mock.On("Add", ctx, card)}
}

func (_c *CardRepository_Add_Call) Run(run func(ctx context.Context, card *entities.Card)) *CardRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Card))
	})
	return _c
}

func (_c *CardRepository_Add_Call) Return(_a0 error) *CardRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Add_Call) RunAndReturn(run func(context.Context, *entities.Card) error) *CardRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *CardRepository) GetByID(ctx context.Context, userID identityvo.UserID, id vos.CardID) (*entities.Card, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) (*entities.Card, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.CardID) *entities.Card); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.CardID) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CardRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - id vos.CardID
func (_e *CardRepository_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *CardRepository_GetByID_Call {
	return &CardRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *CardRepository_GetByID_Call) Run(run func(ctx context.Context, userID identityvo.UserID, id vos.CardID)) *CardRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.CardID))
	})
	return _c
}

func (_c *CardRepository_GetByID_Call) Return(_a0 *entities.Card, _a1 error) *CardRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_GetByID_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.CardID) (*entities.Card, error)) *CardRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, pagination
func (_m *CardRepository) List(ctx context.Context, userID identityvo.UserID, pagination vos.Pagination) ([]entities.Card, error) {
	ret := _m.Called(ctx, userID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Pagination) ([]entities.Card, error)); ok {
		return rf(ctx, userID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identityvo.UserID, vos.Pagination) []entities.Card); ok {
		r0 = rf(ctx, userID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identityvo.UserID, vos.Pagination) error); ok {
		r1 = rf(ctx, userID, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID identityvo.UserID
//   - pagination vos.Pagination
func (_e *CardRepository_Expecter) List(ctx interface{}, userID interface{}, pagination interface{}) *CardRepository_List_Call {
	return &CardRepository_List_Call{Call: _e.mock.On("List", ctx, userID, pagination)}
}

func (_c *CardRepository_List_Call) Run(run func(ctx context.Context, userID identityvo.UserID, pagination vos.Pagination)) *CardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identityvo.UserID), args[2].(vos.Pagination))
	})
	return _c
}

func (_c *CardRepository_List_Call) Return(_a0 []entities.Card, _a1 error) *CardRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_List_Call) RunAndReturn(run func(context.Context, identityvo.UserID, vos.Pagination) ([]entities.Card, error)) *CardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, card
func (_m *CardRepository) Update(ctx context.Context, card *entities.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - card *entities.Card
func (_e *CardRepository_Expecter) Update(ctx interface{}, card interface{}) *CardRepository_Update_Call {
	return &CardRepository_Update_Call{Call: _e.mock.On("Update", ctx, card)}
}

func (_c *CardRepository_Update_Call) Run(run func(ctx context.Context, card *entities.Card)) *CardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Card))
	})
	return _c
}

func (_c *CardRepository_Update_Call) Return(_a0 error) *CardRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Card) error) *CardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
