// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	m := &MockManager{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// MockManager is an autogenerated mock type for the manager.Manager interface.
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

func (_m *MockManager) Driver() database.Driver {
	ret := _m.Called()
	if returnFunc, ok := ret.Get(0).(func() database.Driver); ok {
		return returnFunc()
	}
	return ret.Get(0).(database.Driver)
}

func (_m *MockManager) DBTX(ctx context.Context) database.DBTX {
	ret := _m.Called(ctx)
	if returnFunc, ok := ret.Get(0).(func(context.Context) database.DBTX); ok {
		return returnFunc(ctx)
	}
	if ret.Get(0) == nil {
		return nil
	}
	return ret.Get(0).(database.DBTX)
}

func (_m *MockManager) BeginTx(ctx context.Context, opts database.TxOptions) (database.Tx, error) {
	ret := _m.Called(ctx, opts)
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.TxOptions) (database.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	var r0 database.Tx
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(database.Tx)
	}
	return r0, ret.Error(1)
}

func (_m *MockManager) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		return returnFunc(ctx)
	}
	return ret.Error(0)
}

func (_m *MockManager) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		return returnFunc(ctx)
	}
	return ret.Error(0)
}
