// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrator creates a new instance of MockMigrator.
func NewMockMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrator {
	m := &MockMigrator{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// MockMigrator is an autogenerated mock type for the migration.Migrator interface.
type MockMigrator struct {
	mock.Mock
}

type MockMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrator) EXPECT() *MockMigrator_Expecter {
	return &MockMigrator_Expecter{mock: &_m.Mock}
}

func (_m *MockMigrator) Up(ctx context.Context) error {
	ret := _m.Called(ctx)
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		return returnFunc(ctx)
	}
	return ret.Error(0)
}

func (_m *MockMigrator) Down(ctx context.Context, steps int) error {
	ret := _m.Called(ctx, steps)
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		return returnFunc(ctx, steps)
	}
	return ret.Error(0)
}

func (_m *MockMigrator) Force(ctx context.Context, version int) error {
	ret := _m.Called(ctx, version)
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		return returnFunc(ctx, version)
	}
	return ret.Error(0)
}

func (_m *MockMigrator) Version(ctx context.Context) (uint, bool, error) {
	ret := _m.Called(ctx)
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint, bool, error)); ok {
		return returnFunc(ctx)
	}
	return ret.Get(0).(uint), ret.Get(1).(bool), ret.Error(2)
}
