name: "FinancialControlAPI"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  K8S_NAMESPACE: financialcontrol
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      # - name: "Golang Linter"
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     version: v1.29

      - name: "Unit Tests"
        run: go test --coverprofile tests/coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/config.Production.yaml
        env:
          mssql.connectionString: ${{ secrets.SQL_CONNECTION_STRING }}
          security.jwtSecret: ${{ secrets.JWT_SECRET }}

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Financial API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/financial_api:latest
            ${{ env.DOCKER_USERNAME }}/financial_api:v${{ github.run_number }}

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: deploy
    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy Namespace
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            .k8s/namespaces/financialcontrol.yaml

      - name: Deploy (Financial Control API)
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ env.DOCKER_USERNAME }}/financial_api:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/financialapi-dp.yaml
            .k8s/services/financialapi-svc.yaml
            .k8s/certmanager/issuer.yaml
            .k8s/ingress/ingress.yaml

      # - name: "Deploy to Heroku"
      #   uses: akhileshns/heroku-deploy@v3.11.10
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     usedocker: true
