name: "FinancialControlAPI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  K8S_NAMESPACE: bank
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Build"

    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      # - name: "Golang Linter"
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     version: v1.29

      - name: "Unit Tests"
        run: go test --coverprofile tests/coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/config.Production.yaml
        env:
          mssql.connectionString: ${{ secrets.SQL_CONNECTION_STRING }}
          security.jwtSecret: ${{ secrets.JWT_SECRET }}

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Financial API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/financial_api:latest
            ${{ env.DOCKER_USERNAME }}/financial_api:v${{ github.run_number }}

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    name: "Deploy"
    environment:
      name: deploy

    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      - name: "Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
